# Quarkus datasource configuration
quarkus.package.jar.type=uber-jar
quarkus.datasource.jdbc.url=jdbc:sqlite:./projects.db
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.quinoa.build-dir=dist
quarkus.langchain4j.ollama.devservices.enabled=false
quarkus.native.additional-build-args=--initialize-at-run-time=org.jline.terminal.impl.ffm.CLibrary,--initialize-at-run-time=org.jline.terminal.impl.ffm.FfmNativePty,--initialize-at-run-time=org.jline.terminal.impl.ffm.FfmTerminalProvider,--initialize-at-run-time=org.jline.nativ

# Chat/LLM service configuration
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.model-name=llama3.2
quarkus.langchain4j.ollama.temperature=0.7
quarkus.langchain4j.ollama.timeout-seconds=120
quarkus.langchain4j.ollama.num-predict=-1
quarkus.langchain4j.ollama.num-ctx=0

# Embedding service configuration
quarkus.langchain4j.ollama.embedding-enabled=true
quarkus.langchain4j.ollama.embedding-model-name=qwen3-embedding
quarkus.langchain4j.ollama.embedding-base-url=http://localhost:11434
quarkus.langchain4j.ollama.embedding-dimension=384
quarkus.langchain4j.ollama.embedding-max-results=5